USE HOTEL;
CREATE TABLE HOTELS1(
CITY VARCHAR(50),
NAME VARCHAR(200),
STARS INT ,
ROOM_TYPE VARCHAR(50),
PRICE_PER_NIGHT INT,
LOCATION VARCHAR(250)
);
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("RAJASTHAN","AMRITARA MANAK HAVELI",4,"ROYAL ROOM", 7600,"SONORAN KA BAS,JODHPUR,RAJASTHAN"),
("RAJASTHAN","LALLGARH PALACE",4,"DELUXE ROOM",7000,"GANGANAGAR ROAD,BIKANER,RAJASTHAN"),
("RAJASTHAN","PARK REGIS HOTEL",4,"DELUXE ROOM",5000,"AJMER ROAD,JAIPUR,RAJASTHAN");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("GUJARAT","LEMON TREE PREMIER",4,"DELUXE ROOM",5000,"SABARMATI RIVERFRONT ,AHMEDABAD,GUJARAT"),
("GUJARAT","HOTEL EXPRESS TOWERS",4,"STANDARD ROOM",4500,"ALKAPURI,VADODRA,GUJARAT"),
("GUJARAT","THE GATEWAY HOTEL",5,"STANDARD ROOM",7000,"ATHWA,SURAT,GUJARAT"),
("GUJARAT","WELCOMHOTEL",5,"DELUXE ROOM",9000,"ALKAPURI,VADODRA,GUJARAT"),
("DELHI","THE ROYAL PLAZA",4,"DELUXE ROOM",7000,"ASHOKA ROAD,DELHI"),
("DELHI","THE METROPOLITAN HOTEL ",5,"DELUXE ROOM",8000,"CONNAUGHT PLACE");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("DELHI","THE TAJ MAHAL ",5,"DELUXE ROOM",12000,"NO.1 MANSINGH ROAD,NEW DELHI"),
("DELHI","THE TAJ MAHAL ",5,"LUXURY ROOM",15000,"NO.1 MANSINGH ROAD,NEW DELHI");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("LEH LADAKH","THE GRAND DRAGON",4,"STANDARD ROOM",8000,"OLD ROAD SHEYNAM , LEH LADAKH"),
("LEH LADAKH","THE GRAND DRAGON",4,"DELUXE ROOM",12000,"OLD ROAD SHEYNAM,LEH LADAKH"),
("LEH LADAKH","HOTEL SHANGRILA",3,"STANDARD ROOM",6000,"OLD ROAD,LEH LADAKH"),
("LEH LADAKH","HOTEL SHANGRILA",3,"DELUXE ROOM",8000,"OLD ROAD,LEH LADAKH");
USE HOTEL;
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("ANDAMAN AND NICOBAR ISLANDS","SENTINEL",3,"STANDARD ROOM",5000,"PHOENIX BAY,ANDAMAN AND NICOBAR ISLANDS"),
("ANDAMAN AND NICOBAR ISLANDS","SENTINEL",3,"DELUXE ROOM",7000,"PHOENIX BAY,ANDAMAN AND NICOBAR ISLANDS");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("ANDAMAN AND NICOBAR ISLANDS","SEA SHELL",4,"STANDARD ROOM",6000,"MARINE HILL,ANDAMAN AND NICOBAR ISLANDS"),
("ANDAMAN AND NICOBAR ISLANDS","SEA SHELL",4,"DELUXE ROOM",8000,"MARINE HILL,ANDAMAN AND NICOBAR ISLANDS");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("SIKKIM","THE ELIGN NOR-KHILL",4,"DELUXE ROOM",8000,"PALJOR STADIUM ROAD,GANGTOK,SIKKIM"),
("SIKKIM","THE ELIGN NOR-KHILL",4,"SUITE ",15000,"PALJOR STADIUM ROAD,GANGTOK,SIKKIM"),
("SIKKIM","THE ROYAL PLAZA",4,"DELUXE ROOM",6000,"DEORALI,GANGTOK,SIKKIM"),
("SIKKIM","THE ROYAL PLAZA",4,"SUITE",10000,"DEORALI,GANGTOK,SIKKIM");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("KERALA","THE GRAND HYATT",5,"SUITE",20000,"BOLGATTY ISLAND,KOCHI,KERALA"),
("KERALA","TRIDENT",5,"DELUXE ROOM",8000,"WILLINGDON,KOCHOI,KERALA"),
("KERALA","TRIDENT",5,"SUITE",15000,"WILLINGDON,KOCHOI,KERALA"),
("KERALA","FOUR POINTS",4,"DELUXE ROOM",5000,"KAKKANAD,KOCHI,KERALA");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("KOLKATA","THE OBEROI GRAND",5,"DELUXE ROOM",12000,"JAWAHARLAL NEHRU ROAD,KOLKATA"),
("KOLKATA","THE LALIT GREAT EASTERN",5,"DELUXE ROOM",9000,"OLD HOUSE COURT STREET , KOLKATA"),
("KOLKATA","THE SONNET",4,"DELUXE ROOM",6000,"SALT LAKE,KOLKATA"),
("KOLKATA","THE GOLDEN PARK",4,"DELUXE ROOM",5000,"HO CHI MINH SARANI,KOLKATA");
INSERT INTO HOTELS1(CITY,NAME,STARS,ROOM_TYPE,PRICE_PER_NIGHT,LOCATION)
VALUES
("RAJASTHAN","HOLIDAY INN",4,"DELUXE ROOM", 7000,"SARDAR PATEL ROAD ,JAIPUR,RAJASTHAN");